### ISSUE TITLE
Strange issue?

### ISSUE THREAD

**Issue by PicklePenger** [emerysteele/minecraft-server-status-bot#2]
`D:\My Stuff\Discord Bots\Server Status\minecraft-server-status-bot>node app.js
Ready. Logged as Server Status#3855.
Updating bot status
(node:5280) UnhandledPromiseRejectionWarning: FetchError: request to https://mcapi.ca/ping/all/173.3.187.18225565 failed, reason: getaddrinfo ENOTFOUND mcapi.ca
    at ClientRequest.<anonymous> (D:\My Stuff\Discord Bots\Server Status\minecraft-server-status-bot\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I followed the directions exactly yet I get this error.

**Comment by PicklePenger** [comment]
I've edited the script to adjust mcapi.ca to mcapi.us to account for my US Location. After that, the bot runs and gives me the ready status. However, if I try to use a command like mc!status, it gives me this... 

![image](https://user-images.githubusercontent.com/80995339/111876910-27fdf380-8977-11eb-9b2d-31f66177ce0b.png)

There appears to be a missing dependency, despite the fact that I had made sure to install all dependencies listed in the README setup. Any idea what might be causing this issue? Thanks in advance.

**Comment by PicklePenger** [comment]
Not to mention, the status of the bot displays as such...

![image](https://user-images.githubusercontent.com/80995339/111876968-727f7000-8977-11eb-96c3-badb287953a3.png)

The name is different than displayed as the console simply because I gave it a nickname in the Discord client. This occurs with or without the nickname applied.

**Comment by emerysteele** [comment]
Looks like mcapi.ca is down. Unfortunately not directly interchangeable with mcapi.us as they have a different url request format & I believe the responses are different too.

For ex the request url for mcapi.ca was: https://mcapi.ca/ping/all/mc.hypixel.net:25565
While mcapi.us is: https://mcapi.us/server/status?ip=mc.hypixel.net&port=25565

So the bot will need to be modified a bit to work with mcapi.us
I originally tried using mcapi.us but ran into rate limit issues

**Comment by PicklePenger** [comment]
I had been trying to access mcapi.ca for a while now and have had no luck, so I adjusted the bot to use the mcapi.us domain adjusted to fit their different format accordinly. I was looking at the modules and found that when running `npm i fs`, I checked its module folder and found this: 

![image](https://user-images.githubusercontent.com/80995339/111877672-af993180-897a-11eb-9654-04e7dfedd06d.png)

Excuse me if I am rather ignorant, as I am somewhat new to all of this, but was this a former dependency that now goes under a different name or is no longer supported?

**Comment by PicklePenger** [comment]
Reading the errors, though, it doesn't appear to be an issue with fs and that should be a default Node module nonetheless...

**Comment by PicklePenger** [comment]
Okay, upon further examination, 'clean' shows up a few times in the JavaScript when referring to the MOTD and it says it is undefined. mcapi.us must use different values that aren't defined as such... That's unfortunate.

**Comment by PicklePenger** [comment]
Can confirm. By rewriting body.players.online to body.players.now in the JavaScript, adjust for mcapi.us, the bot now displays this:

![image](https://user-images.githubusercontent.com/80995339/111880245-aca13f80-8980-11eb-9ce9-a3468980d482.png)

That is because the value is now defined.

**Comment by emerysteele** [comment]
Yeah, there's a few changes like that that need to be made to make it compatible with mcapi.us.

Just did a quick edit, for the most part, this app.js should work:
[app.zip](https://github.com/emerysteele/minecraft-server-status-bot/files/6176068/app.zip)

**Comment by PicklePenger** [comment]
Oh, thank you. I had already edited myself but I'll keep that as a backup. Thanks for the help.

**Comment by emerysteele** [comment]
No worries! Thanks for informing me of the issue.

Not sure if mcapi.ca is coming back, looks like the maintainer of that project is MIA. I should probably update this repo to use mcapi.us instead.

**Comment by PicklePenger** [comment]
It likely isn't, it seems. Thank you so much, though, as that updated script works perfectly. This bot was exactly what I was looking for and I'm glad the issue was able to be resolved!
